[2024-10-03T19:51:29.656+0530] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-03T19:51:29.668+0530] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_dag.load_data manual__2024-10-03T14:21:07.180648+00:00 [queued]>
[2024-10-03T19:51:29.676+0530] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_dag.load_data manual__2024-10-03T14:21:07.180648+00:00 [queued]>
[2024-10-03T19:51:29.676+0530] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-03T19:51:29.701+0530] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): load_data> on 2024-10-03 14:21:07.180648+00:00
[2024-10-03T19:51:29.708+0530] {standard_task_runner.py:72} INFO - Started process 21952 to run task
[2024-10-03T19:51:29.712+0530] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'data_ingestion_dag', 'load_data', 'manual__2024-10-03T14:21:07.180648+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmpzemjqw3x']
[2024-10-03T19:51:29.714+0530] {standard_task_runner.py:105} INFO - Job 103: Subtask load_data
[2024-10-03T19:51:29.769+0530] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_dag.load_data manual__2024-10-03T14:21:07.180648+00:00 [running]> on host Nithesh-Kumar.localdomain
[2024-10-03T19:51:29.875+0530] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_ingestion_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-03T14:21:07.180648+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-03T14:21:07.180648+00:00'
[2024-10-03T19:51:29.876+0530] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-03T19:51:29.903+0530] {base.py:84} INFO - Retrieving connection 'target_***_conn'
[2024-10-03T19:51:29.919+0530] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/username/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/username/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/username/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/username/blackstraw/airflow/airflow/dags/data_ingestion_dag.py", line 104, in load_data
    for row in rows:
TypeError: 'NoneType' object is not iterable
[2024-10-03T19:51:29.926+0530] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_dag, task_id=load_data, run_id=manual__2024-10-03T14:21:07.180648+00:00, execution_date=20241003T142107, start_date=20241003T142129, end_date=20241003T142129
[2024-10-03T19:51:29.951+0530] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-03T19:51:29.951+0530] {standard_task_runner.py:124} ERROR - Failed to execute job 103 for task load_data ('NoneType' object is not iterable; 21952)
Traceback (most recent call last):
  File "/home/username/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/username/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/username/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/username/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/username/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/username/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/username/blackstraw/airflow/airflow/dags/data_ingestion_dag.py", line 104, in load_data
    for row in rows:
TypeError: 'NoneType' object is not iterable
[2024-10-03T19:51:29.968+0530] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-03T19:51:29.988+0530] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-03T19:51:29.989+0530] {local_task_job_runner.py:245} INFO - ::endgroup::
