[2024-10-03T17:14:05.080+0530] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-03T17:14:05.091+0530] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_dag.extract_data manual__2024-10-03T11:38:51.365877+00:00 [queued]>
[2024-10-03T17:14:05.096+0530] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_dag.extract_data manual__2024-10-03T11:38:51.365877+00:00 [queued]>
[2024-10-03T17:14:05.097+0530] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-10-03T17:14:05.121+0530] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_data> on 2024-10-03 11:38:51.365877+00:00
[2024-10-03T17:14:05.125+0530] {standard_task_runner.py:72} INFO - Started process 26033 to run task
[2024-10-03T17:14:05.128+0530] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'data_ingestion_dag', 'extract_data', 'manual__2024-10-03T11:38:51.365877+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmpsqrwqrqe']
[2024-10-03T17:14:05.130+0530] {standard_task_runner.py:105} INFO - Job 64: Subtask extract_data
[2024-10-03T17:14:05.173+0530] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_dag.extract_data manual__2024-10-03T11:38:51.365877+00:00 [running]> on host Nithesh-Kumar.localdomain
[2024-10-03T17:14:05.235+0530] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_ingestion_dag' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-03T11:38:51.365877+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-03T11:38:51.365877+00:00'
[2024-10-03T17:14:05.236+0530] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-03T17:14:05.247+0530] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/username/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/username/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/username/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/username/blackstraw/airflow/airflow/dags/data_ingestion_dag.py", line 30, in extract_data
    print("All csv files are already scanned. No new files" + csv_files)
TypeError: can only concatenate str (not "list") to str
[2024-10-03T17:14:05.250+0530] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=data_ingestion_dag, task_id=extract_data, run_id=manual__2024-10-03T11:38:51.365877+00:00, execution_date=20241003T113851, start_date=20241003T114405, end_date=20241003T114405
[2024-10-03T17:14:05.270+0530] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-03T17:14:05.271+0530] {standard_task_runner.py:124} ERROR - Failed to execute job 64 for task extract_data (can only concatenate str (not "list") to str; 26033)
Traceback (most recent call last):
  File "/home/username/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/username/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/username/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/username/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/username/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/username/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/username/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/username/blackstraw/airflow/airflow/dags/data_ingestion_dag.py", line 30, in extract_data
    print("All csv files are already scanned. No new files" + csv_files)
TypeError: can only concatenate str (not "list") to str
[2024-10-03T17:14:05.302+0530] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-03T17:14:05.316+0530] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-03T17:14:05.331+0530] {local_task_job_runner.py:245} INFO - ::endgroup::
